### ISSUE TITLE
jamovi.proto is out of sync with the jamovi server

### ISSUE THREAD

**Issue by sjentsch** [jamovi/jmvcore#23]
The protocol definition on the server (https://github.com/jamovi/jamovi/blob/current-dev/server/jamovi/server/jamovi.proto) differs from the one in inst/jamovi.proto

**Comment by sjentsch** [comment]
I would at least need title and hasTitle from AnalysisResponse.

**Comment by sjentsch** [comment]
Suggestion: If the definitions for `VariableLevel` and `MeasureType`  are moved up into `//ANALYSIS`, you could just split that file at `//CLIENT`. The only remaining difference would then be `DataSetSchema.MeasureType` vs `MeasureType` in the `ResultsOutput`.

**Comment by jonathon-love** [comment]
> I would at least need title and hasTitle from AnalysisResponse

i think that these are missing means that you don't need them. i think these are for when the user has customised the title. i think the title you want is the one in the root `ResultsGroup`.

>  If the definitions for VariableLevel and MeasureType are moved up into //ANALYSIS, you could just split that file at //CLIENT. The only remaining difference would then be DataSetSchema.MeasureType vs MeasureType in the ResultsOutput.

yeah, i've tried to do this ... i think there's differences in the way RProtoBuf and other protobuf libraries work, so i've had to maintain this difference.

**Comment by sjentsch** [comment]
re [1]: No, I am afraid I need `title` and `hasTitle`. I am nearly done with a function `describe_omv` which will appear in the next version of `jmvReadWrite`. It permits you to create a data set description (like in https://github.com/sjentsch/examples4jamovi/blob/main/Analysis%20of%20variance/Alcohol%20Attitudes.omv) programmatically.
re [2]: I initially was opposed to the thought of having different versions of `jamovi.proto`, but I understand your point (the risk of messing things up, or ). The `jamovi.proto` version in `jmvcore` covers the needs for `jmv` but not what I want it for (in [1]), which unfortunately means that I have to carry a third version of `jamovi.proto`. But as I said, I understand your prioritization (playing safe). If you at some point change your mind about it, I am willing to do help (e..g, with testing).

**Comment by jonathon-love** [comment]
> No, I am afraid I need title and hasTitle

i'm not sure this is the case (you may be right), but i've pushed those mods to `jamovi.proto` now
